//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJCHospitalConsol.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_T
    {
        public int ConsultationID { get; set; }
        public int PatID { get; set; }
        public string PatSocialSecurityID { get; set; }
        public int DocID { get; set; }
        public string DocName { get; set; }
        public System.DateTime StartTime { get; set; }
        public int RoomNumber { get; set; }
        public double Price { get; set; }
    
        public virtual Patient_T Patient_T { get; set; }
        public virtual User_T User_T { get; set; }
    }
}
